---
- name: Install PostgreSQL on database server group
  hosts: database
  become: true
  gather_facts: false

  tasks:
    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: "postgresql-{{ postgresql_version }}"
        state: present
        update_cache: true

    - name: Set custom Data directory in config
      ansible.builtin.lineinfile:
        path: /var/lib/postgresql/{{ postgresql_version }}/main/postgresql.conf
        regexp: "^data_directory"
        line: "data_directory = '{{ postgresql_data_directory }}'"
        mode: "0644"
        create: true
        state: present

    - name: Set custom Data directory in service
      ansible.builtin.lineinfile:
        path: /lib/systemd/system/postgresql.service
        regexp: "^Environment=PGDATA="
        line: "Environment=PGDATA={{ postgresql_data_directory }}"
        state: present

    - name: Start PostgreSQL service
      ansible.builtin.systemd_service:
        name: postgresql
        state: started
        enabled: true
